root = 'application/virtual/api'

require "#{root}/base_api"
require "#{root}/alive"
require "#{root}/cd"
require "#{root}/led"
require "#{root}/media"
require "#{root}/radio_led"
require "#{root}/telephone"
# require "#{root}/ccm"
# require "#{root}/ike_sensors"
# require "#{root}/key"
# require "#{root}/lamp"
# require "#{root}/monitor"
# require "#{root}/radio_gfx"
# require "#{root}/speed"
